name: estuary
version: '0.0.0.1'
synopsis: Platform for collaboration and learning through live coding
description: Please see README.md
category: Web
author: David Ogborn and contributors
maintainer: ogbornd@mcmaster.ca
copyright: 2015-20 David Ogborn and contributors
license: GPL-3
homepage: http://github.com/dktr0/estuary/blob/stable/README.md

# Our build is a Simple build with a preTest hook for running tests with
# puppeteer.
# build-type: Custom
# custom-setup:
#   dependencies:
#     - base
#     - Cabal == 1.22.8.2
#     - filepath
#     - directory

flags:
  build-test-executables:
    description: Build the test executables.
    manual: true
    default: false

dependencies:
  - base
  - estuary-common
  - reflex
  - reflex-dom
  - reflex-dom-core
  - lens
  - tidal
  - tidal-parse
  - punctual
  - musicw >= 0.3.8
  - hosc
  - containers
  - safe
  - ghcjs-base
  - ghcjs-dom
  - text
  - text-show
  - array
  - ghcjs-prim
  - data-default
  - transformers
  - file-embed
  - time
  - monad-loops
  - aeson
  - bytestring
  - parsec
  - parsec-numbers
  - reflex-dom-contrib
  - mtl
  - haskell-src-exts
  - haskellish
  - timeNot
  - seis8s
  - deepseq
  - microspec
  - tempi
  - split
  - witherable
  

library:
  source-dirs:
    - ./src
# Add common to stack.yaml (and dependencies) and reexport those modules here

_test-executable: &test-executable
  when:
    - condition: flag(build-test-executables)
      then:
        buildable: true
      else:
        buildable: false

executables:
  Estuary:
    main: Main.hs
    source-dirs:
      - ./app
    dependencies:
      - estuary
    when:
    - condition: flag(build-test-executables)
      then:
        buildable: false
      else:
        buildable: true

  simple-test:
    <<: *test-executable
    main: Simple.hs
    source-dirs:
      - ./test
    dependencies:
      - estuary
      - bytestring-handle
      - hspec
      - async

  interaction-test:
    <<: *test-executable
    main: Interaction.hs
    source-dirs:
      - ./test
    js-sources:
      - ./test/Estuary/Test/protocol-inspector.js
    dependencies:
      - estuary
      - estuary-common
      - bytestring-handle
      - hspec
      - async

################################
# TESTS
################################

_test-base: &test-base
  source-dirs:
    - ./test
  dependencies:
    - estuary
    - hspec

tests:
  clientTest:
    main: ClientTests.hs
    source-dirs: ./tests
    dependencies:
      - microspec >= 0.2.1.3
      - estuary
