name: estuary-server
version: '0.0.0.1'
synopsis: Platform for collaboration and learning through live coding
description: Please see README.md
category: Web
author: David Ogborn and contributors
maintainer: ogbornd@mcmaster.ca
copyright: 2015-20 David Ogborn and contributors
license: GPL-3
homepage: http://github.com/dktr0/estuary/blob/master/README.md

dependencies:
  - base
  - stm
  - estuary-common
  - containers
  - directory
  - filepath
  - htaglib
  - text
  - json
  - aeson
  - bytestring
  - http-types
  - websockets
  - wai
  - warp
  - tls
  - warp-tls
  - wai-websockets
  - wai-app-static
  - wai-extra
  - time
  - sqlite-simple
  - mtl
  - text-show

library:
  source-dirs:
    - ./src

executables:
  EstuaryServer:
    main: Main.hs
    source-dirs:
      - ./app
    dependencies:
      - estuary-server
    ghc-options: -threaded
