name: estuary-common
version: '0.0.0.1'
synopsis: Platform for collaboration and learning through live coding
description: Please see README.md
category: Web
author: David Ogborn and contributors
maintainer: ogbornd@mcmaster.ca
copyright: 2015-20 David Ogborn and contributors
license: GPL-3
homepage: http://github.com/dktr0/estuary/blob/stable/README.md

dependencies:
  - base
  - text
  - time
  - containers
  - text
  - aeson
  - tempi
  - parsec
  - witherable
  - mtl

extra-source-files:
  - package.yaml

library:
  source-dirs:
    - ./src
